export const QUESTION: string[] = [
  "An affirmation pls...",
  "Hey!",
  "Can I have an affirmation?",
  "*Otter noises*",
  "I miss you",
  "Hmmmmm...",
];

export const AFFIRMATIONS: string[] = [
  "*Squirrel noises*",
  "I miss you",
  "You look great today",
  "You are the best",
  "Take it easy today",
  "Don’t forget that you are awesome",
  "You’re my favorite",
  "Keep your head up",
  "Don’t stress it",
  "You are beautiful",
  "I’m glad you are here",
  "You’re my best friend",
  "Don’t change at all",
  "Keep being you",
  "I like the way you keep a positive attitude",
  "I will keep you in my thoughts today",
  "Did you wake up looking that beautiful?",
  "You look gorgeous every day",
  "I love being your partner",
  "Kick today’s butt",
  "You do you so well",
  "You amaze me",
  "You are it for me",
  "You are killing it",
  "You are a go-getter",
  "I love your cooking",
  "Thank you for taking care of me",
  "You do so much, and I appreciate it",
  "You are the best partner I could ask for",
  "You make me laugh",
  "You make me smile",
  "Thanks for being a real friend",
  "You are easy on the eyes",
  "I can’t tell you what you mean to me",
  "I think you’re the bee’s knees",
  "I want you to know that I care",
  "You are a great support system",
  "Don’t ever think you aren’t loved",
  "You’re my favorite person",
  "You amaze me",
  "Thanks for keeping your cool",
  "I love that you are strong, even in a crisis",
  "No one could do what you do",
  "You are an inspiration to me",
  "You make me want to work harder",
  "I don’t know what I would do without you",
  "Thank you for laughing at my jokes",
  "I like that you are in my corner",
  "Thanks for showing me the bright side of every situation",
  "I can’t remember my life without you",
  "I love how your brain works",
  "You are a 10",
  "Let me tell you, you’re my dream woman",
  "I can’t wait to make you my wife",
  "You are going to be a great partner",
  "I want to start a family with you",
  "You have a great sense of style",
  "I would love to take you somewhere nice",
  "I am happy to be your mate",
  "I am learning a lot from you",
  "I can’t wait to build our life together",
  "I love the memories we make with each other",
  "You make everything better",
  "Being with you is good for me",
  "I like your personality",
  "You make each day exciting",
  "Thank you for choosing me",
  "I love being your sidekick",
  "You are my snowball",
];
