export const LOVE: string[] = [
  "You make me happy.",
  "You dare me to be a better version of myself.",
  "You follow me and you push me.",
  "You love me in the times when I’m not capable to love myself.",
  "You forgive me quickly.",
  "You understand me. And when you don’t, you do everything and you go all in to get clarity about the things you don’t understand.",
  "You respect my boundaries. And you dare to cross them when you are sure you know better.",
  "You accept my sadness and my anger and you live in harmony with them.",
  "You see and you love the next best version of me.",
  "You open yourself up for me.",
  "You are truthful and vulnerable with me.",
  "You are doing everything to become a better woman for yourself and for us.",
  "You are courageous.",
  "You go to therapy.",
  "You take care of your body.",
  "You nourish your relationship with your family.",
  "You have the most wonderful eyes.",
  "You have a gentle, innocent smile that always comforts me.",
  "You are sad and you share your sadness with me.",
  "You have the smoothest skin. I could spend hours just watching and caressing it.",
  "You have beautiful soft hands.",
  "Your have a beautiful woman’s butt for therapeutic squeezing.",
  "Your energy is clean and bright.",
  "You have a gentle and calming voice that soothes me when I’m upset.",
  "The stories you’re writing inspire me.",
  "You are the only person who makes me laugh more then I can make myself laugh.",
  "You amuse me, make me laugh and inspire me by reading me your stories out loud.",
  "You know so much about everything and I love it when you tell me about history and all the other things I know little about.",
  "You know how to calm me down when I’m sad.",
  "You share your power with me when I’m weak.",
  "You have a unique style and you’re cool.",
  "You are stunning, sexy and attractive.",
  "Your sexuality is strong and you share it with me.",
  "You are smart and a fast learner.",
  "You managed to gain more of my thrust then anyone before.",
  "You are the first person I gave my financial dependence to.",
  "You teach me how to love unconditionally.",
  "You let me be myself and you encourage me to find more of myself.",
  "You invest in yourself.",
  "You trust my intuition.",
  "You made the first move.",
  "You care for me and you look after me.",
  "You love and you care about our fur babies.",
  "You respect my friends and you make an effort together with me to nourish that relationships.",
  "When I’m stuck, you help me find a solution.",
  "You always drop me off and pick me up when I travel alone.",
  "You give your best to make it easy for me when life gets tough.",
  "You care to know how I feel in every moment.",
  "You are reliable.",
  "You bravely listen and accept my complaints.",
  "You care about my relationship with my parents.",
  "You care about my success and my happiness.",
  "You care about my body, you love it and you accept it.",
  "You have a strong faith.",
  "You let me give you a massage and you dedicate yourself to give me a massage.",
  "You chose me and you continue to choose me.",
  "You kiss me soft and tender, always and everywhere.",
  "You remind me to drink water.",
  "You encourage me to write.",
  "You know how to force me to the edge of fear.",
  "You are gentle and thoughtful.",
  "You dare to show me all your faces.",
  "You write a journal.",
  "You are clean.",
  "You love and enjoy the nature and the sea.",
  "You are ready to do any house choir I ask you to.",
  "You wash the dishes more often then I do.",
  "You are ready to take risk and make life changing decisions for me.",
  "You threw away most of your chlothes I hated.",
  "You are ready to build our big bright future with me.",
  "You are ready to do anything to heal my pain.",
  "You share with me all that you have.",
  "I’m not afraid to fall, ’cause I know you are there to catch me.",
  "You care about your male friends and you are actively working on those relationships.",
  "People love you and everyone enjoys your company.",
  "You know how to feed us when I’m not capable to do that.",
  "You are strongly connected to your roots and your parent’s home towns.",
  "You tought me to understand and enjoy nature on a deeper level.",
  "You are able to live any life style life brings us.",
  "You are tearing down my walls gentle and patient.",
  "You don’t hesitate to hush me down and lead us when it’s necessary.",
  "You listened to your heart when we started our journey and you did all the right moves.",
  "When you kissed me for the first time, it was at the right moment at the right place. It will always be one of my favorite memories.",
  "You care about my opinion and we make all the important decisions together.",
  "You call me all the sweet nicknames and you kiss me when you leave and come back home.",
  "You hug me and hold me before we fall asleep.",
  "You are wonderful for at least 100 more reasons.",
  "I love you for at least 100 more reasons.",
  "I love how you are so witty",
  "You inspire me how you are healing your inner child",
  "You have fun child like energy",
  "You appreciate my gifts no matter how big or small.",
];
